In [13]:
import pandas as pd
import numpy as np
df=pd.read_csv('/content/student data_set.csv')
df

,Student_ID,Name,Department,Python_Marks,SQL_Marks,Maths_Marks,Attendance_Percentage,CGPA
0,STU001,Aditi Sharma,CSE,85,78,90,92,8.43
1,STU002,Rohan Verma,CSE,72,68,75,80,7.17
2,STU003,Priya Patel,IT,45,38,52,70,4.50
3,STU004,Arjun Singh,CSE,92,88,95,96,9.17
4,STU005,Neha Jain,IT,30,55,42,65,4.23
5,STU006,Kavya Joshi,AIML,88,84,76,91,8.27
6,STU007,Rahul Gupta,CSE,67,73,69,85,6.97
7,STU008,Sneha Mehta,IT,91,86,89,94,8.87
8,STU009,Vivek Mishra,AIML,54,61,58,72,5.77
9,STU010,Ananya Rao,CSE,79,82,87,89,8.27
10,STU011,Karan Malhotra,IT,34,29,48,60,3.70
11,STU012,Ishita Kulkarni,AIML,95,93,91,98,9.30
12,STU013,Manav Agarwal,CSE,62,57,65,77,6.13
13,STU014,Pooja Soni,IT,76,71,80,88,7.57
14,STU015,Aditya Choudhary,AIML,41,44,39,68,4.13
15,STU016,Meera Iyer,CSE,83,90,85,95,8.60
16,STU017,Sahil Khan,IT,58,47,63,74,5.60
17,STU018,Diya Bansal,AIML,87,79,92,90,8.60
18,STU019,Yash Thakur,CSE,28,36,31,55,3.17
19,STU020,Tanya Desai,IT,74,81,77,86,7.73

In [14]:

print("First 5 students:")
print(df.head())

print("Dataset shape:")
print(df.shape)

print("Column names:")
print(df.columns)

print("Dataset information:")
df.info()

First 5 students:
  Student_ID          Name Department  Python_Marks  SQL_Marks  Maths_Marks  \
0     STU001  Aditi Sharma        CSE            85         78           90
1     STU002   Rohan Verma        CSE            72         68           75
2     STU003   Priya Patel         IT            45         38           52
3     STU004   Arjun Singh        CSE            92         88           95
4     STU005     Neha Jain         IT            30         55           42

   Attendance_Percentage  CGPA
0                     92  8.43
1                     80  7.17
2                     70  4.50
3                     96  9.17
4                     65  4.23
Dataset shape:
(20, 8)
Column names:
Index(['Student_ID', 'Name', 'Department', 'Python_Marks', 'SQL_Marks',
       'Maths_Marks', 'Attendance_Percentage', 'CGPA'],
      dtype='object')
Dataset information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 8 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Student_ID             20 non-null     object
 1   Name                   20 non-null     object
 2   Department             20 non-null     object
 3   Python_Marks           20 non-null     int64
 4   SQL_Marks              20 non-null     int64
 5   Maths_Marks            20 non-null     int64
 6   Attendance_Percentage  20 non-null     int64
 7   CGPA                   20 non-null     float64
dtypes: float64(1), int64(4), object(3)
memory usage: 1.4+ KB

In [15]:

print("Missing Values:")
print(df.isnull().sum())


print("Duplicate Rows:", df.duplicated().sum())

print("Duplicate Student IDs:", df["Student_ID"].duplicated().sum())

for col in ["Python_Marks", "SQL_Marks", "Maths_Marks"]:
    print(col, "Invalid Values:",
          ((df[col] < 0) | (df[col] > 100)).sum())

print("Invalid Attendance:",
      ((df["Attendance_Percentage"] < 0) |
       (df["Attendance_Percentage"] > 100)).sum())

Missing Values:
Student_ID               0
Name                     0
Department               0
Python_Marks             0
SQL_Marks                0
Maths_Marks              0
Attendance_Percentage    0
CGPA                     0
dtype: int64
Duplicate Rows: 0
Duplicate Student IDs: 0
Python_Marks Invalid Values: 0
SQL_Marks Invalid Values: 0
Maths_Marks Invalid Values: 0
Invalid Attendance: 0

In [16]:
print("--------------------AVERAGE OF CGPA----------------------------")
AVG=df['CGPA'].mean()
print(AVG)

--------------------AVERAGE OF CGPA----------------------------
6.808999999999999

In [17]:
print('------------------------------ASSIGNING GRADES-----------------------------=-------')
df["Grade"] = ""

for i in range(len(df)):
    if df["CGPA"][i] >= 9:
        df.loc[i, "Grade"] = "A+"
    elif df["CGPA"][i] >= 8:
        df.loc[i, "Grade"] = "A"
    elif df["CGPA"][i] >= 7:
        df.loc[i, "Grade"] = "B"
    elif df["CGPA"][i] >= 6:
        df.loc[i, "Grade"] = "C"
    elif df["CGPA"][i] >= 5:
        df.loc[i, "Grade"] = "D"
    else:
        df.loc[i, "Grade"] = "F"

(df[["Name",'Department','Python_Marks','SQL_Marks','Maths_Marks',"CGPA", "Grade"]])

------------------------------ASSIGNING GRADES-----------------------------=-------

,Name,Department,Python_Marks,SQL_Marks,Maths_Marks,CGPA,Grade
0,Aditi Sharma,CSE,85,78,90,8.43,A
1,Rohan Verma,CSE,72,68,75,7.17,B
2,Priya Patel,IT,45,38,52,4.50,F
3,Arjun Singh,CSE,92,88,95,9.17,A+
4,Neha Jain,IT,30,55,42,4.23,F
5,Kavya Joshi,AIML,88,84,76,8.27,A
6,Rahul Gupta,CSE,67,73,69,6.97,C
7,Sneha Mehta,IT,91,86,89,8.87,A
8,Vivek Mishra,AIML,54,61,58,5.77,D
9,Ananya Rao,CSE,79,82,87,8.27,A
10,Karan Malhotra,IT,34,29,48,3.70,F
11,Ishita Kulkarni,AIML,95,93,91,9.30,A+
12,Manav Agarwal,CSE,62,57,65,6.13,C
13,Pooja Soni,IT,76,71,80,7.57,B
14,Aditya Choudhary,AIML,41,44,39,4.13,F
15,Meera Iyer,CSE,83,90,85,8.60,A
16,Sahil Khan,IT,58,47,63,5.60,D
17,Diya Bansal,AIML,87,79,92,8.60,A
18,Yash Thakur,CSE,28,36,31,3.17,F
19,Tanya Desai,IT,74,81,77,7.73,B

In [18]:
print("-------------------Python_Marks-----------------")
import numpy as np
python_marks = df["Python_Marks"]
print("Highest Python Marks:", np.max(python_marks))
print("Lowest Python Marks:", np.min(python_marks))
print("Average Python Marks:", np.mean(python_marks))

-------------------Python_Marks-----------------
Highest Python Marks: 95
Lowest Python Marks: 28
Average Python Marks: 67.05

In [19]:
print("-------------------SQL_Marks-----------------")
import numpy as np
SQL_Marks = df["SQL_Marks"]
print("Highest SQL Marks:", np.max(SQL_Marks))
print("Lowest SQL Marks:", np.min(SQL_Marks))
print("Average SQL Marks:", np.mean(SQL_Marks))

-------------------SQL_Marks-----------------
Highest SQL Marks: 93
Lowest SQL Marks: 29
Average SQL Marks: 67.0

In [20]:
print("-------------------Maths_Marks-----------------")
import numpy as np
Maths_Marks = df["Maths_Marks"]
print("Highest Maths Marks:", np.max(Maths_Marks))
print("Lowest MATHS Marks:", np.min(Maths_Marks))
print("Average Maths Marks:", np.mean(Maths_Marks))

-------------------Maths_Marks-----------------
Highest Maths Marks: 95
Lowest MATHS Marks: 31
Average Maths Marks: 70.2

In [21]:
result = []

for i in df["CGPA"]:
    if i >= 4:
        result.append("Pass")
    else:
        result.append("Fail")

df["Result"] = result

df[["Name", "CGPA", "Result"]]

                Name  CGPA Result
0       Aditi Sharma  8.43   Pass
1        Rohan Verma  7.17   Pass
2        Priya Patel  4.50   Pass
3        Arjun Singh  9.17   Pass
4          Neha Jain  4.23   Pass
5        Kavya Joshi  8.27   Pass
6        Rahul Gupta  6.97   Pass
7        Sneha Mehta  8.87   Pass
8       Vivek Mishra  5.77   Pass
9         Ananya Rao  8.27   Pass
10    Karan Malhotra  3.70   Fail
11   Ishita Kulkarni  9.30   Pass
12     Manav Agarwal  6.13   Pass
13        Pooja Soni  7.57   Pass
14  Aditya Choudhary  4.13   Pass
15        Meera Iyer  8.60   Pass
16        Sahil Khan  5.60   Pass
17       Diya Bansal  8.60   Pass
18       Yash Thakur  3.17   Fail
19       Tanya Desai  7.73   Pass

In [22]:
print('----------------------------Total Marks of Each Student-------------------------------')

df["Total_Marks"] = (
    df["Python_Marks"] +
    df["SQL_Marks"] +
    df["Maths_Marks"]
)
df[["Name", "Python_Marks", "SQL_Marks",
          "Maths_Marks", "Total_Marks"]]

----------------------------Total Marks of Each Student-------------------------------

                Name  Python_Marks  SQL_Marks  Maths_Marks  Total_Marks
0       Aditi Sharma            85         78           90          253
1        Rohan Verma            72         68           75          215
2        Priya Patel            45         38           52          135
3        Arjun Singh            92         88           95          275
4          Neha Jain            30         55           42          127
5        Kavya Joshi            88         84           76          248
6        Rahul Gupta            67         73           69          209
7        Sneha Mehta            91         86           89          266
8       Vivek Mishra            54         61           58          173
9         Ananya Rao            79         82           87          248
10    Karan Malhotra            34         29           48          111
11   Ishita Kulkarni            95         93           91          279
12     Manav Agarwal            62         57           65          184
13        Pooja Soni            76         71           80          227
14  Aditya Choudhary            41         44           39          124
15        Meera Iyer            83         90           85          258
16        Sahil Khan            58         47           63          168
17       Diya Bansal            87         79           92          258
18       Yash Thakur            28         36           31           95
19       Tanya Desai            74         81           77          232

In [23]:
print('--------------Top Performing Student-------------------------')
highest_cgpa = max(df["CGPA"])

for i in range(len(df)):
    if df.loc[i, "CGPA"] == highest_cgpa:
        print(df.loc[i, "Name"])
        print(df.loc[i, "Department"])
        print(df.loc[i, "CGPA"])
        print(df.loc[i, "Grade"])

--------------Top Performing Student-------------------------
Ishita Kulkarni
AIML
9.3
A+

In [24]:
print('----------------------Attendance Analyse-------------------')

attendance = df["Attendance_Percentage"]

print("Highest Attendance:", np.max(attendance))
print("Lowest Attendance:", np.min(attendance))
print("Average Attendance:", np.mean(attendance))

----------------------Attendance Analyse-------------------
Highest Attendance: 98
Lowest Attendance: 55
Average Attendance: 81.25

In [25]:
print('------------------STUDENT PERFORMANCE ANALYTICS SYSTEM-----------------------')
total_students = len(df)

average_cgpa = df["CGPA"].mean()

highest_cgpa = df["CGPA"].max()
lowest_cgpa = df["CGPA"].min()

passed = (df["CGPA"] >= 4).sum()
failed = (df["CGPA"] < 4).sum()

pass_percentage = (passed / total_students) * 100
fail_percentage = (failed / total_students) * 100

top_performer = df.loc[df["CGPA"].idxmax(), "Name"]

python_average = df["Python_Marks"].mean()
numpy_average = df["SQL_Marks"].mean()
pandas_average = df["Maths_Marks"].mean()

best_subject = max(
    python_average,
    numpy_average,
    pandas_average
)

if best_subject == python_average:
    best_subject = "Python"
elif best_subject == numpy_average:
    best_subject = "SQL"
else:
    best_subject = "Maths"

print("Total Students:", total_students)
print("Class Average CGPA:", round(average_cgpa, 2))
print("Highest CGPA:", highest_cgpa)
print("Lowest CGPA:", lowest_cgpa)
print("Passing Students:", passed)
print("Failing Students:", failed)
print("Pass Percentage:", round(pass_percentage, 2), "%")
print("Fail Percentage:", round(fail_percentage, 2), "%")
print("Top Performer:", top_performer)
print("Best Subject:", best_subject)
print('------------------------PROJECT COMPLETED SUCCESSFULLY----------------')

------------------STUDENT PERFORMANCE ANALYTICS SYSTEM-----------------------
Total Students: 20
Class Average CGPA: 6.81
Highest CGPA: 9.3
Lowest CGPA: 3.17
Passing Students: 18
Failing Students: 2
Pass Percentage: 90.0 %
Fail Percentage: 10.0 %
Top Performer: Ishita Kulkarni
Best Subject: Maths
------------------------PROJECT COMPLETED SUCCESSFULLY----------------